name: taskati_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.0.0
  google_fonts: ^6.1.0
  gap: ^3.0.1
  image_picker: ^1.0.7
  intl: ^0.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  date_picker_timeline: ^1.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true


  assets:
    - assets/